baseURL = "https://gofish.dev/"
languageCode = "en-us"

title = "GoFish"
externalTitle = "GoFish"
subtitle = "Keep your fish fresh!"
theme = "kraiklyn"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4

[[menu.shortcuts]]
name = "GoFish on Github"
url = "https://github.com/tinned-fish/gofish"
weight = 10

[[menu.shortcuts]]
name = "gofish.dev on Github"
url = "https://github.com/tinned-fish/gofish.dev"
weight = 20
