baseURL = "/"
languageCode = "en-us"

title = "GoFish"
subtitle = "Keep your fish fresh!"
theme = "kraiklyn"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[[menu.shortcuts]]
name = "GoFish on Github"
url = "https://github.com/piccobit/gofish"
weight = 10

[[menu.shortcuts]]
name = "gofi.sh on Github"
url = "https://github.com/piccobit/gofish.dev"
weight = 10
